<?php include "header.phtml"; ?>

<main role="main" class="container">

    <h2>Welcome to UBCEats. 🧀🌭🍕</h2>

    <p>This project was developed over the course of 18 hours by <a href="https://github.com/iandelrio">Ian Del Rio</a>, <a href="https://gottardo.me">Andrea Gottardo</a> and <a href="http://falkirks.com">Noah Heyl</a> at <a href="https://www.nwhacks.io">nwHacks '18</a>.</p>

    <h3>Inspiration</h3>

    <p>Information regarding food items at UBC is hard to find. It is easy to look for venues, but not so easy to access their menus. And most importantly, there's no centralized place to look for venues based on your food preferences. We want to change that.</p>

    <h3>What it does</h3>

    <p>UBCEats is a search engine that allows you to look for venues at UBC offering specific food items. For instance, you can search for <mark>pizza</mark> and get back all places at UBC where you can get some kind of pizza. Additionally, you can filter results by the distance of the venue, and by whether your meal plan is accepted or not.</p>

    <h3>How we built it</h3>

    <p>UBCEats is powered by a PHP/MySQL backend, and a HTML/CSS frontend based on Bootstrap. Entering of food items into the database was performed both by scraping where feasible, and by human-powered manual insertion. Geo-location is powered by JavaScript.</p>

    <h3>Challenges we ran into</h3>

    <p>Nothing too serious. One major issue was that UBC Food Services provides the vast majority of their menu in PDF format. It was almost impossible to scrape those programmatically.</p>

    <h3>Accomplishments that we're proud of</h3>

    <p>We're offering something useful to the entire UBC community! In particular, students can look for places that accept their meal plan easily.</p>

    <h3>What's next for UBCEats</h3>

    <ul>
        <li>Users should be able to update the database with new food items, new prices, as menus get updated.</li>
        <li>Users should be able to leave reviews.</li>
        <li>Food items descriptions should be more specific and relevant.</li>
        <li>Provide images of food items, where possible.</li>
    </ul>

</main>

<?php include "footer.phtml"; ?>