<?php include "header.phtml"; ?>

<main role="main" class="container">

    <h2>Welcome to UBCEats. 🧀🌭🍕</h2>

    <p>This is our CPSC304 project. We hope you like it!</p>


    <div class="card">
        <div class="card-body">
            <h4>Query inspector</h4>
            <p>At the top of every page you will see a little "Queries" box. Clicking it will reveal a queries pane. This pane captures all the SQL queries used to generate a specific page. Most of our queries and all of our queries needed for grading are visible this way. There is also a handy way to reset the database through the query inspector. The following queries are excluded from the inspector:</p>

            <ul>
                <li>Integrity checking on the main page with <code>SHOW TABLES</code></li>
                <li><code>INSERT</code> command for reviews (is lost in redirect chain)</li>
                <li>SQL scripts for database resetting</li>
            </ul>
        </div>
    </div>
    <br>

    <div class="card">
        <div class="card-body">
            <h4>Admin status</h4>
            <p>If you are logged in to an admin account, you should see a lightning bolt in the top right. If you don't see this you will be missing the admin menus from your interface.</p>
        </div>
    </div>

</main>

<?php include "footer.phtml"; ?>