<?php include "header.phtml"; ?>

<main role="main" class="container">

    <h2>Add a location</h2>

    <form method="get" action="/addlocation">
        <?php
        if ($didInsert) {
            if (is_null($error)) { ?>
            <div class="alert alert-success" role="alert">
                <p>The new location <code><?php echo $lastName; ?></code> was successfully pushed to the database.</p>
            </div>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <p>Sorry, but the location insertion failed. MySQL returned the following error:</p>
                <code><?php echo $error; ?></code>
            </div>
        <?php } } ?>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name">
            <small class="form-text text-muted">The name of a location, for instance <mark>Student Union Building</mark> or <mark>Ponderosa Commons</mark>.</small>
        </div>
        <div class="form-group">
            <label for="address">Address</label>
            <input type="text" class="form-control" id="address" name="address">
            <small class="form-text text-muted">The address of the location. Street number and name only, as in <mark>5959 University Blvd</mark>.</small>
        </div>
        <div class="form-group">
            <label for="latitude">Latitude</label>
            <input type="text" class="form-control" id="latitude" name="latitude">
            <small class="form-text text-muted">The latitude of the location, for instance <mark>49.26</mark>.</small>
        </div>
        <div class="form-group">
            <label for="longitude">Longitude</label>
            <input type="text" class="form-control" id="longitude" name="longitude">
            <small class="form-text text-muted">The longitude of the location, for instance <mark>-123.25</mark>.</small>
        </div>
        <button type="submit" class="btn btn-primary">Insert into database</button>
    </form>

</main>

<?php include "footer.phtml"; ?>