<?php include "header.phtml"; ?>

<main role="main" class="container">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/list">Brands</a></li>
            <li class="breadcrumb-item"><?php echo $brand['name']; ?></li>
        </ol>
    </nav>

    <?php if($brand !== null){?>
    <div class="jumbotron">
        <a class="btn btn-primary  btn-sm float-right"
           href="<?php echo $brand['url']; ?>"><span class="ion-link"></span>  <?php echo parse_url($brand['url'])['host']; ?></a>
        <h1 class="display-4"><i class="ion-pizza"></i> <?php echo $brand['name']; ?></h1>
        <p class="lead text-justify"><?php echo(($brand['desc'] == "") ? "<span class=\"text-muted\">We currently don't have a description for this brand in our database.</span>" : $brand['desc']); ?></p>



    </div>

        <h2><i class="ion-ios-list"></i> Menu <span class="badge badge-secondary"><?php echo sizeof($menu); ?></span>
        </h2>

    <ul class="list-group">
        <?php foreach ($menu as $item): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="/brand/<?php echo urlencode($brand['name']) ?>/<?php echo urlencode($item["name"]) ?>"><?php echo $item["name"] ?></a>
            <div class="align-ri">
                <span class="badge badge-primary">$<?php echo number_format((float)$item["price"], 2, '.', ''); ?></span>
                <span class="badge <?php echo ($item["total"] > 75 ? 'badge-success' : ($item["total"] > 50 ? 'badge-warning' : 'badge-danger')) ?>"><?php echo($item["total"] == null ? "N/A" : $item["total"] . '%') ?></span>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
        <?php if (sizeof($menu) == 0) { ?>
            <div class="alert alert-warning" role="alert">
                <b>Sad!</b> This brand has no food items in the database. How about <a href="/addfooditem">adding
                    one</a> now?
            </div>
        <?php } ?>
        <br/>

        <h2><i class="ion-ios-location"></i> Locations <span
                    class="badge badge-secondary"><?php echo sizeof($locations); ?></span></h2>
        <div class="row">
    <?php foreach ($locations as $location): ?>
    <div class="col-md-4">
        <div class="card" style="margin: 10px">
            <img class="card-img-top" src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $location['latitude'] ?>,<?php echo $location['longitude'] ?>&zoom=15&key=AIzaSyAMKNkuj3va5nL4RSsutcFdsFl_zTiqJ88&scale=false&size=400x250&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7C<?php echo $location['latitude'] ?>,<?php echo $location['longitude'] ?>" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><?php echo $location['name'] ?></h5>

                <h6 class="card-subtitle mb-2 text-muted"><?php echo $location['address'] ?></h6>
                <p class="card-text">
                    <small>
                        <i class="ion-clock"></i> <?php echo($location['opensAt'] != null ? ($location['opensAt'] == -1 ? "Not open today" : $location['opensAt'] . " - " . $location['closesAt'] . " <span class=\"text-muted\">today</span>") : "No times for today.") ?>
                    </small>
                </p>
            </div>
        </div>
    </div>

    <?php endforeach; ?>
    </div>
            <?php if (sizeof($locations) == 0) { ?>
                <div class="alert alert-warning" role="alert">
                    <b>Sad!</b> This brand has no locations in the database. How about <a href="/addlocation">adding
                        one</a> now?
                </div>
            <?php } ?>
    </div>

    <?php
    }
    else{
        echo "That brand doesn't exist.";
    }
    ?>
</main>

<?php include "footer.phtml"; ?>