<?php include "header.phtml"; ?>

<main role="main" class="container">
    <?php if($brand !== null){?>
    <div class="jumbotron">
        <h1 class="display-4"><?php echo $brand['name']; ?></h1>
        <p class="lead"><?php echo $brand['desc']; ?></p>
    </div>

    <h2>Menu</h2>

    <ul class="list-group">
        <?php foreach ($menu as $item): ?>
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <a href="/brand/<?php echo urlencode($brand['name']) ?>/<?php echo urlencode($item["name"]) ?>"><?php echo $item["name"] ?></a>
            <div class="align-ri">
                <span class="badge badge-primary badge-pill">$<?php echo $item["price"] ?></span>
                <span class="badge badge-warning badge-pill"><?php echo ($item["total"] == null ? "N/A" : $item["total"]) ?></span>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>


    <h2>Locations</h2>
    <div class="row">
    <?php foreach ($locations as $location): ?>
    <div class="col-md-4">
        <div class="card" style="margin: 10px">
            <img class="card-img-top" src="https://maps.googleapis.com/maps/api/staticmap?center=<?php echo $location['latitude'] ?>,<?php echo $location['longitude'] ?>&zoom=15&key=AIzaSyAMKNkuj3va5nL4RSsutcFdsFl_zTiqJ88&scale=false&size=400x250&maptype=roadmap&format=png&visual_refresh=true&markers=size:mid%7Ccolor:0xff0000%7Clabel:%7C<?php echo $location['latitude'] ?>,<?php echo $location['longitude'] ?>" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title"><?php echo $location['name'] ?></h5>

                <h6 class="card-subtitle mb-2 text-muted"><?php echo $location['address'] ?></h6>
                <p class="card-text">Open: <?php echo ($location['opensAt'] != null ? ($location['opensAt'] == -1 ? "Not open today" : $location['opensAt'] . "-" . $location['closesAt']) : "No times for today.") ?></p>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
    </div>

    <?php
    }
    else{
        echo "That brand doesn't exist.";
    }
    ?>
</main>

<?php include "footer.phtml"; ?>