<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="favicon.ico">

    <title>UBCEats</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom style for UBCEats -->
    <link href="/css/ubceats.css" rel="stylesheet">

    <!-- Iconic icons support -->
    <link href="/css/open-iconic-bootstrap.css" rel="stylesheet">
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

    <!-- Highlight css -->
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css">

    <!-- UBC font: PT Sans -->
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand mb-0 h1" href="/">UBCEats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
</nav>




<main role="main" class="container">
    <?php if (isset($configMissing)): ?>
        <div class="card mb-3">
            <div class="card-header bg-info text-white"> <i class="ion-wand"></i> UBCEats setup wizard</div>
            <div class="card-body">
                <h5 class="card-title">Your next step is creating a db.json file</h5>
                <p>Create this file in the main directory of the project. It will tell UBCEats how to connect to your database. Once you make this file, just reload the page and a connection will be attempted. The file should be of the format</p>
                <pre><code class="json">{
   "hostname": "hostname here",
   "user": "username here",
   "password": "password here",
   "dbName": "database name here"
}</code></pre>
            </div>
        </div>
    <?php endif;?>

    <div class="card mb-3">
        <div class="card-header bg-danger text-white"> Error!</div>
        <div class="card-body">
            <h5 class="card-title">Could not establish database connection</h5>
            <p class="card-text">UBCeats can't connect to the database right now. Try checking your internet connection and the <code>db.json</code> file.</p>
        </div>
    </div>


    </main>

<?php include "footer.phtml"; ?>