<?php include "header.phtml"; ?>

<main role="main" class="container">


    <h2><? echo $foodItem["name"]; ?></h2>


    <form action="/vote" method="post">
        <input type="hidden" class="form-control" name="brandName" value="<? echo $brand; ?>">
        <input type="hidden" class="form-control" name="foodItemName" value="<? echo $foodItem["name"]; ?>">

        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="isUpvote" name="isUpvote">
            <label class="form-check-label" for="isUpvote">Do you want to upvote?</label>
        </div>

        <div class="form-group">
            <label for="review">Review</label>
            <textarea class="form-control" id="review" name="review" rows="2"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Post review</button>
    </form>


</main>

<?php include "footer.phtml"; ?>