<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="favicon.ico">

    <title>UBCEats</title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom style for UBCEats -->
    <link href="/css/ubceats.css" rel="stylesheet">

    <!-- Iconic icons support -->
    <link href="/css/open-iconic-bootstrap.css" rel="stylesheet">
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

    <!-- UBC font: PT Sans -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="/">UBCEats</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/about">WTF is this?</a>
            </li>
        </ul>
        <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
            <?php if (isset($_SESSION["username"])) {
                ?><li class="nav-item order-2 order-md-1"><span class="navbar-text">Logged in as <b><?php echo $_SESSION["username"]; ?></b>.</span></li> <?php
            } else { ?><li class="nav-item order-2 order-md-1"><a href="#" class="nav-link" title="settings"><i class="fa fa-cog fa-fw fa-lg"></i></a></li>
            <li class="dropdown order-1">
                <button type="button" id="dropdownMenu1" data-toggle="dropdown" class="btn btn-outline-secondary dropdown-toggle">Login <span class="caret"></span></button>
                <ul class="dropdown-menu dropdown-menu-right mt-1">
                    <li class="p-3">
                        <form class="form" role="form" method="get" action="/login">
                            <div class="form-group">
                                <input name="username" placeholder="Username" class="form-control form-control-sm" type="text" required="">
                            </div>
                            <div class="form-group">
                                <input name="password" placeholder="Password" class="form-control form-control-sm" type="password" required="">
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">Login</button>
                            </div>
                        </form>
                    </li>
                </ul>
            </li>
            <?php } ?>
        </ul>
    </div>
</nav>

<?php
foreach ($GLOBALS["mysqlLogs"] as $item){
    echo "<main role=\"main\" class=\"container\"><code>".$item."</code></main>";
}
?>
