<?php include "header.phtml"; ?>

<main role="main" class="container">
    <form id="searchForm">
        <div class="form-group">
            <input type="text" class="form-control form-control-lg" id="search-term" aria-describedby="search-term"
                   placeholder="Look up any food item at UBC... ">
            <small id="search-help" class="form-text text-muted">
                Try searching for
                <mark><a href="/search/pizza">pizza</a></mark>
                or
                <mark><a href="/search/burger">burger</a></mark>
                .
            </small>

        </div>
    </form>
    <br/>
    <div class="card">
        <div class="card-body">
            <h5>Some random facts
                <small class="text-muted">Because we know you are a data-driven person</small>
            </h5>
            <small>
                <p>The most expensive restaurant is
                    <mark>
                        <a href="/brand/<?php echo $price["max"]["brandName"] ?>"><?php echo $price["max"]["brandName"] ?></a>
                    </mark>
                    . The average price of an item there is
                    <mark><?php echo $price["max"]["price"] ?></mark>
                    .
                </p>

                <p>The least expensive restaurant is
                    <mark>
                        <a href="/brand/<?php echo $price["min"]["brandName"] ?>"><?php echo $price["min"]["brandName"] ?></a>
                    </mark>
                    . The average price of an item there is
                    <mark><?php echo $price["min"]["price"] ?></mark>
                    .
                </p>
            </small>
        </div>
    </div>
</main>

<?php include "footer.phtml"; ?>
