<?php include "header.phtml"; ?>

<main role="main" class="container">

    <h2>Delete a location</h2>

    <form method="get" action="/rmlocation">
        <?php
        if ($didRemove) {
            if (is_null($error)) { ?>
            <div class="alert alert-success" role="alert">
                <p>The location <code><?php echo $lastName; ?></code> was successfully removed from the database.</p>
            </div>
        <?php } else { ?>
            <div class="alert alert-danger" role="alert">
                <p>Sorry, but the location deletion failed. MySQL returned the following error:</p>
                <code><?php echo $error; ?></code>
            </div>
        <?php } } ?>
        <div class="form-group">
            <label for="location">Select a location to delete</label>
            <select class="form-control" id="location" name="location">
                <?php foreach ($locations as $location) {
                    echo "<option>".$location["name"]." | ".$location["address"]."</option>";
                } ?>
            </select>
        </div>
        <button type="submit" class="btn btn-danger">Delete from database</button>
    </form>

</main>

<?php include "footer.phtml"; ?>